In [12]:
import numpy as np

count = 5
notas = np.zeros(count, dtype=float)
i = 0
print("### INFORME NOTAS DE 1 A 100 ###")
while i < count:
    y = i + 1
    try:
        nota = float(input(f'Digite a nota {y}: '))
        if (nota < 0 or nota > 100):
            print("Nota inválida")
            continue                
    except:
        print("Informe um valor válido")
        continue    
    notas[i] = nota
    i = y

# realizando os calculos
percentagem_aprovacao = 60
total_notas = notas.sum
media =  float(notas.sum()/notas.size)
if media >= percentagem_aprovacao:
    print(f'Aluno Aprovado com média {media}')
else:
    print(f'Aluno Reprovado com média {media}')

### INFORME NOTAS DE 1 A 100 ###


Digite a nota 1:  10
Digite a nota 2:  110


Nota inválida


Digite a nota 2:  78
Digite a nota 3:  89
Digite a nota 4:  29
Digite a nota 5:  70


Aluno Reprovado com média 55.2


In [13]:
import random
import numpy as np

matrix = np.zeros((5,5), dtype=int)

for x in range(0, 5):
    for y in range(0, 5):
        value = random.randint(0, 100)
        matrix[x,y] = value

print(matrix)
for x in matrix:
    print(np.sum(x))

[[82 73 78 52 31]
 [85 19 57 90 97]
 [65 76 50 89 66]
 [63 63  9 34 17]
 [89 23 48 72 24]]
316
348
346
186
256


In [5]:
import random

def questao3(ent1, ent2):
    if (ent1 - ent2) < 0:
        print("ent1 - ent2 é negativo")
    if (ent1 * ent2) < 0:
        print("ent1 * ent2 é negativo")
    if (ent1 + ent2) < 0:
        print("ent1 * ent2 é negativo")

print("### Utilize S para sim ou N para não ###")
valorEntrada = ""
x = True
while x:
    valorEntrada = input("Deseja Informar os valores use, s ou n: ")
    if (valorEntrada == 's' or valorEntrada == 'n'):
        x = False
    
if (valorEntrada == 's'):
    ent1 = int(input("Informe o valor 1"))
    ent2 = int(input("Informe o valor 2"))
else:    
    ent1 = random.randint(-9, 9)
    ent2 = random.randint(-9, 9)

print(f'Valores informados: Valor 1: {ent1} e Valor 2: {ent2}')

questao3(ent1, ent2)

### Utilize S para sim ou N para não ###


Deseja Informar os valores use, s ou n:  s
Informe o valor 1 -2
Informe o valor 2 1


Valores informados: Valor 1: -2 e Valor 2: 1
ent1 - ent2 é negativo
ent1 * ent2 é negativo
ent1 * ent2 é negativo


In [10]:
def altera_nos_pares(caracter, mensagem = "", qtd_caracter_mensagem = 0):    
    mensagem_sifrada = ""
    c = 0
    while c < qtd_caracter_mensagem:
        if (c % 2 == 0):        
            mensagem_sifrada = mensagem_sifrada + caracter
        else:
            mensagem_sifrada = mensagem_sifrada + mensagem[c]
        c += 1
        
    return mensagem_sifrada
    
mensagem = "Aulas de Python daquele jeito"
nova_mensagem = altera_nos_pares("*", mensagem, len(mensagem))
print(nova_mensagem)

*u*a* *e*P*t*o* *a*u*l* *e*t*
